### ISSUE TITLE
Ruby has mismatched versions of bundler gem

### ISSUE THREAD

**Issue by sgerrand** [circleci/circleci-images#112]
I've observed some odd behaviour with the Docker images created for Ruby. They have version 1.15.4 of the bundler gem installed, but it thinks that its latest version is 1.16.0.

(edit: I originally discovered this in the Docker images for v2.2.8, but have subsequently found it affects

### Some examples:
Image: `circleci/ruby:2.4.2`:
```
$ docker run --rm -it circleci/ruby:2.4.2 bundler version
Bundler version 1.15.4
```
```
$ docker run --rm -it circleci/ruby:2.4.2 bundle version
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle (LoadError)
	from /usr/local/bin/bundle:23:in `<main>'
```

Image:  `circleci/ruby:2.2`
```
$ docker run --rm -it circleci/ruby:2.2 bundle version
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.16.0/exe/bundle (LoadError)
        from /usr/local/bin/bundle:23:in `<main>'
```
```
$ docker run --rm -it circleci/ruby:2.2 /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/exe/bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2017-12-01 commit )
```

Image: `circleci/ruby:2.2-node-browsers`
```
$ docker run --rm -it circleci/ruby:2.2-node-browsers bundle version
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.16.0/exe/bundle (LoadError)
        from /usr/local/bin/bundle:23:in `<main>'
```
```
$ docker run --rm -it circleci/ruby:2.2-node-browsers /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/exe/bundle version
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2017-12-01 commit )
```

**Comment by sgerrand** [comment]
It appears that this is caused by a lingering environment variable in the image: `BUNDLER_VERSION=1.16.0`.

**Comment by sgerrand** [comment]
🙋 Updated the issue to reflect that this issue is affecting _all_ of CircleCI's Ruby images.

**Comment by renchap** [comment]
Solved in #113, no idea when will will be deployed.

**Comment by sgerrand** [comment]
It's not resolved yet. After pulling the Ruby image changes that were built and pushed in https://circleci.com/gh/circleci/circleci-images/3340, the problem remains:
```
$ docker run --rm -it circleci/ruby:2.3.5 bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2017-12-01 commit )
```
```
$ docker run --rm -it circleci/ruby:2.3.5 bundler version
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:308:in `activate_bin_path'
	from /usr/local/bin/bundler:23:in `<main>'
```

**Comment by renchap** [comment]
Ping @DanToml

**Comment by DanToml** [comment]
@renchap #113 has been deployed, please let us know if you see any specific images that are broken.

**Comment by aaronjensen** [comment]
Thanks for the fix, but how do I use it on circleci? I seem to still get the old image. Do you purge your image cache from time to time to allow for upgrades like this?

**Comment by fernfernfern** [comment]
@aaronjensen Try adding the hash of the new image to your config file to bypass the caching

```
image: ruby@sha256:91fa706ab0d1c49a1cf69b1803187e3663577477cb8e73542cdad1c8e2ecd771
```
